import type { ChannelGroup } from './types';

export const CHANNEL_DEFINITIONS: Omit<ChannelGroup, 'enabled'>[] = [
  { id: 'ae', name: 'A&E', icon: 'img/channels/a-e.jpg', channelIds: ['AETV'] },
  { id: 'abc', name: 'ABC News', icon: 'img/channels/abc-news.jpg', channelIds: ['ABCNews'] },
  { id: 'access', name: 'Access', icon: 'img/channels/access.jpg', channelIds: ['AccessHollywood'] },
  { id: 'aljazeera', name: 'Al Jazeera', icon: 'img/channels/al-jazeera-english.jpg', channelIds: ['AlJazeeraEnglish'] },
  { id: 'ap', name: 'Associated Press', icon: 'img/channels/associated-press.jpg', channelIds: ['AssociatedPress'] },
  { id: 'bbc', name: 'BBC', icon: 'img/channels/bbc.jpg', channelIds: ['BBC', 'bbcnews'] },
  { id: 'bet', name: 'BET', icon: 'img/channels/bet-networks.jpg', channelIds: ['BETNetworks'] },
  { id: 'bloomberg', name: 'Bloomberg', icon: 'img/channels/bloomberg.jpg', channelIds: ['Bloomberg', 'UCV61VqLMr2eIhH4f51PV0gA'] },
  { id: 'bravo', name: 'Bravo', icon: 'img/channels/bravo.jpg', channelIds: ['VideoByBravo'] },
  { id: 'buzzfeed', name: 'BuzzFeed', icon: 'img/channels/buzzfeed-video.jpg', channelIds: ['BuzzFeedVideo'] },
  { id: 'cbc', name: 'CBC', icon: 'img/channels/cbc-news.jpg', channelIds: ['cbcnews'] },
  { id: 'cbs', name: 'CBS', icon: 'img/channels/cbs.jpg', channelIds: ['CBS', 'CBSNewsOnline', 'CBSEveningNews', 'CBSThisMorning', 'Cbsfacethenation1', 'cbstvdinsideedition'] },
  { id: 'cnbc', name: 'CNBC', icon: 'img/channels/cnbc.jpg', channelIds: ['cnbc', 'UCrp_UI8XtuYfpiqluWLD7Lw'] },
  { id: 'cnn', name: 'CNN', icon: 'img/channels/cnn.jpg', channelIds: ['CNN'] },
  { id: 'comedycentral', name: 'Comedy Central', icon: 'img/channels/comedy-central.jpg', channelIds: ['comedycentral'] },
  { id: 'cspan', name: 'C-SPAN', icon: 'img/channels/cspan.jpg', channelIds: ['CSPAN'] },
  { id: 'enews', name: 'E! News', icon: 'img/channels/enews.jpg', channelIds: ['enews'] },
  { id: 'entertainmenttonight', name: 'Entertainment Tonight', icon: 'img/channels/entertainment-tonight.jpg', channelIds: ['EntertainmentTonight'] },
  { id: 'espn', name: 'ESPN', icon: 'img/channels/espn.jpg', channelIds: ['ESPN'] },
  { id: 'fox', name: 'Fox News', icon: 'img/channels/fox-news.jpg', channelIds: ['FoxNewsChannel', 'FoxBusinessNetwork'] },
  { id: 'global', name: 'Global News', icon: 'img/channels/global-news.jpg', channelIds: ['GlobalToronto'] },
  { id: 'gq', name: 'GQ', icon: 'img/channels/gq.jpg', channelIds: ['GQVideos'] },
  { id: 'guardian', name: 'Guardian', icon: 'img/channels/guadian.jpg', channelIds: ['TheGuardian', 'guardianwires'] },
  { id: 'history', name: 'HISTORY', icon: 'img/channels/history.jpg', channelIds: ['historychannel'] },
  { id: 'hollywoodlife', name: 'HollywoodLife', icon: 'img/channels/hollywood-life.jpg', channelIds: ['hollywoodlife09'] },
  { id: 'huffpost', name: 'HuffPost', icon: 'img/channels/huff-post.jpg', channelIds: ['HuffingtonPost'] },
  { id: 'insider', name: 'INSIDER', icon: 'img/channels/insider.jpg', channelIds: ['UCHJuQZuzapBh-CuhRYxIZrg'] },
  { id: 'latenight', name: 'Late Night', icon: 'img/channels/jimmy-fallon.jpg', channelIds: ['latenight', 'JimmyKimmelLive', 'LateNightSeth', 'UCMtFAi84ehTSYSE9XoHefig', 'LastWeekTonight', 'UCwWhs_6x42TyRM4Wstoq8HA'] },
  { id: 'lifetime', name: 'Lifetime', icon: 'img/channels/lifetime.jpg', channelIds: ['Lifetime'] },
  { id: 'mashable', name: 'Mashable', icon: 'img/channels/mashable.jpg', channelIds: ['mashable'] },
  { id: 'msnbc', name: 'MSNBC', icon: 'img/channels/msnbc.jpg', channelIds: ['msnbcleanforward'] },
  { id: 'nbc', name: 'NBC', icon: 'img/channels/nbc.jpg', channelIds: ['NBC', 'NBCNews', 'TODAYNBC'] },
  { id: 'nowthis', name: 'NowThis News', icon: 'img/channels/nowthis-news.jpg', channelIds: ['nowthismedia'] },
  { id: 'pbs', name: 'PBS', icon: 'img/channels/pbs.jpg', channelIds: ['PBS', 'PBSNewsHour'] },
  { id: 'people', name: 'PeopleTV', icon: 'img/channels/people.jpg', channelIds: ['people'] },
  { id: 'rt', name: 'RT', icon: 'img/channels/rt.jpg', channelIds: ['RussiaToday', 'RuptlyTV'] },
  { id: 'skynews', name: 'Sky News', icon: 'img/channels/skynews.jpg', channelIds: ['skynews'] },
  { id: 'tbs', name: 'TBS', icon: 'img/channels/tbs.jpg', channelIds: ['TBS'] },
  { id: 'telegraph', name: 'The Telegraph', icon: 'img/channels/telegraph.jpg', channelIds: ['telegraphtv'] },
  { id: 'nyt', name: 'New York Times Co.', icon: 'img/channels/the-new-york-times.jpg', channelIds: ['TheNewYorkTimes', 'NewYorkerDotCom', 'NYPost'] },
  { id: 'sun', name: 'The Sun', icon: 'img/channels/the-sun.jpg', channelIds: ['thesunnewspaper'] },
  { id: 'verge', name: 'The Verge', icon: 'img/channels/the-verge.jpg', channelIds: ['TheVerge'] },
  { id: 'time', name: 'TIME', icon: 'img/channels/time.jpg', channelIds: ['TimeMagazine'] },
  { id: 'tmz', name: 'TMZ', icon: 'img/channels/tmz.jpg', channelIds: ['TMZ'] },
  { id: 'usanetwork', name: 'USA Network', icon: 'img/channels/usa-network.jpg', channelIds: ['usanetwork'] },
  { id: 'usatoday', name: 'USA TODAY', icon: 'img/channels/usa-today.jpg', channelIds: ['USATODAY'] },
  { id: 'condenast', name: 'Conde Nast', icon: 'img/channels/vanity-fair.jpg', channelIds: ['VanityFairMagazine', 'Americanvogue'] },
  { id: 'variety', name: 'Variety', icon: 'img/channels/variety.jpg', channelIds: ['Variety'] },
  { id: 'vice', name: 'VICE', icon: 'img/channels/vice.jpg', channelIds: ['vice', 'vicenews'] },
  { id: 'vox', name: 'Vox', icon: 'img/channels/vox.jpg', channelIds: ['voxdotcom'] },
  { id: 'washingtonpost', name: 'Washington Post', icon: 'img/channels/washington-post.jpg', channelIds: ['WashingtonPost'] },
  { id: 'yahoo', name: 'Yahoo', icon: 'img/channels/yahoo.jpg', channelIds: ['yahoo'] },
];
